# Generated by Django 5.0.6 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCategory',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeadParty',
            fields=[
                ('partyname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('add1', models.CharField(blank=True, max_length=200)),
                ('add2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('otherno', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('remark', models.TextField(blank=True)),
            ],
        ),
    ]
