# Generated by Django 5.2.4 on 2025-09-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCategory',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeadCompany',
            fields=[
                ('company', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeadCompanyinfo',
            fields=[
                ('companyname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('add1', models.TextField(blank=True)),
                ('add2', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('mobile', models.TextField(blank=True)),
                ('otherno', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('remark', models.TextField(blank=True)),
                ('term1', models.TextField(blank=True)),
                ('term2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadParty',
            fields=[
                ('partyname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('add1', models.CharField(blank=True, max_length=200)),
                ('add2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('otherno', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('remark', models.TextField(blank=True)),
                ('openingdebit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('openingcredit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayMaster',
            fields=[
                ('entryno', models.AutoField(primary_key=True, serialize=False)),
                ('entrydate', models.DateField()),
                ('partyname', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurMaster',
            fields=[
                ('invno', models.AutoField(primary_key=True, serialize=False)),
                ('invdate', models.DateField()),
                ('partyname', models.CharField(max_length=255)),
                ('add1', models.CharField(blank=True, max_length=255, null=True)),
                ('add2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno', models.BigIntegerField(default=0)),
                ('otherno', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('netamt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amtinwords', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecMaster',
            fields=[
                ('entryno', models.AutoField(primary_key=True, serialize=False)),
                ('entrydate', models.DateField()),
                ('partyname', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleMaster',
            fields=[
                ('invno', models.AutoField(primary_key=True, serialize=False)),
                ('invdate', models.DateField()),
                ('partyname', models.CharField(max_length=255)),
                ('add1', models.CharField(blank=True, max_length=255, null=True)),
                ('add2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno', models.BigIntegerField(default=0)),
                ('otherno', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('netamt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amtinwords', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadItem',
            fields=[
                ('itemname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('op_st', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Op. St.')),
                ('pur_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pur Rate')),
                ('sale_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sale Rate')),
                ('reorder', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reorder')),
                ('remark', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invapp.headcategory')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invapp.headcompany')),
            ],
        ),
        migrations.CreateModel(
            name='PurDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemqty', models.IntegerField()),
                ('itemrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invapp.purmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemqty', models.IntegerField()),
                ('itemrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salemaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invapp.salemaster')),
            ],
        ),
    ]
