# Generated by Django 5.0.6 on 2025-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCompany',
            fields=[
                ('company', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
