# Generated by Django 5.0.6 on 2025-07-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0002_headcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadItem',
            fields=[
                ('itemname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('op_st', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Op. St.')),
                ('pur_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pur Rate')),
                ('sale_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sale Rate')),
                ('reorder', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reorder')),
                ('remark', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invapp.headcategory')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invapp.headcompany')),
            ],
        ),
    ]
