# Generated by Django 5.0.6 on 2025-07-30 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0003_headitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurMaster',
            fields=[
                ('invno', models.AutoField(primary_key=True, serialize=False)),
                ('invdate', models.DateField()),
                ('partyname', models.CharField(max_length=255)),
                ('add1', models.CharField(blank=True, max_length=255, null=True)),
                ('add2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno', models.BigIntegerField(default=0)),
                ('otherno', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('netamt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amtinwords', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invapp.purmaster')),
            ],
        ),
    ]
