# Generated by Django 5.0.6 on 2025-08-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0004_purmaster_purdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purdetails',
            old_name='qty',
            new_name='itemqty',
        ),
        migrations.RenameField(
            model_name='purdetails',
            old_name='rate',
            new_name='itemrate',
        ),
    ]
