# Generated by Django 5.0.6 on 2025-08-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0005_rename_qty_purdetails_itemqty_and_more'),
    ]

    operations = [
    ]
