# Generated by Django 5.0.6 on 2025-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0007_salemaster_saledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMaster',
            fields=[
                ('entryno', models.AutoField(primary_key=True, serialize=False)),
                ('entrydate', models.DateField()),
                ('partyname', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecMaster',
            fields=[
                ('entryno', models.AutoField(primary_key=True, serialize=False)),
                ('entrydate', models.DateField()),
                ('partyname', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
