# Generated by Django 5.2.4 on 2025-08-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0008_paymaster_recmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='headparty',
            name='openingcredit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='headparty',
            name='openingdebit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
