# Generated by Django 5.0.6 on 2025-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0009_headparty_openingcredit_headparty_openingdebit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCompanyinfo',
            fields=[
                ('companyname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('add1', models.TextField(blank=True)),
                ('add2', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('mobile', models.TextField(blank=True)),
                ('otherno', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('remark', models.TextField(blank=True)),
                ('term1', models.TextField(blank=True)),
                ('term2', models.TextField(blank=True)),
            ],
        ),
    ]
